Repository ezsystems/ezplatform-solr-search-engine, pull requests merged in 2019-06, with the labels that each got.

#140 EZP-30638: Upgrade `ezsystems/ezplatform-solr-search-engine` to use Symfony 4 components
  .travis.yml
  bundle/DependencyInjection/EzSystemsEzPlatformSolrSearchEngineExtension.php
  composer.json
  tests/bundle/DependencyInjection/EzPublishEzPlatformSolrSearchEngineExtensionTest.php
  tests/lib/Container/Compiler/AggregateCriterionVisitorPassTest.php
  tests/lib/Container/Compiler/AggregateFacetBuilderVisitorPassTest.php
  tests/lib/Container/Compiler/AggregateSortClauseVisitorPassTest.php
  tests/lib/Search/Gateway/EndpointResolver/NativeEndpointResolverTest.php
  tests/lib/Search/Gateway/EndpointTest.php
  tests/lib/Slot/RemoveTranslationTest.php
Labels: Improvement, Ready for review

#137 EZP-30463: As an Developer, I want to use Solr Cloud
  .travis.yml
  bin/.travis/init_solr.sh
  bundle/DependencyInjection/Configuration.php
  bundle/DependencyInjection/EzSystemsEzPlatformSolrSearchEngineExtension.php
  bundle/Resources/config/services.yml
  lib/Gateway/DistributionStrategy.php
  lib/Gateway/DistributionStrategy/AbstractDistributionStrategy.php
  lib/Gateway/DistributionStrategy/CloudDistributionStrategy.php
  lib/Gateway/DistributionStrategy/StandaloneDistributionStrategy.php
  lib/Gateway/Native.php
  lib/Resources/config/container/solr.yml
  tests/lib/Resources/config/cloud.yml
  tests/lib/Search/Gateway/DistributionStrategy/CloudDistributionStrategyTest.php
  tests/lib/Search/Gateway/DistributionStrategy/StandaloneDistributionStrategyTest.php
  tests/lib/SetupFactory/LegacySetupFactory.php
Labels: Feature, QA Approved

#141 [SF4] Implemented factory for IndexingDepthProvider
  lib/Query/Content/CriterionVisitor/Factory/FullTextFactory.php
  lib/Resources/config/container/solr/criterion_visitors.yml
Labels: Bug, Ready for MERGE
