Repository ezsystems/ezplatform-solr-search-engine, pull requests merged in 2019-10, with the labels that each got.

#150 EZP-30296: Large API subtree delete leads to serious Solr index inconsistencies
  composer.json
  lib/Handler.php
Labels: QA Approved

#136 EZP-30835: Added support for Solr 7.7
  .travis.yml
  bin/.travis/init_solr.sh
  bin/generate-solr-config.sh
  lib/Query/Common/QueryConverter/NativeQueryConverter.php
  lib/Resources/config/solr/schema.xml
Labels: Feature, QA Approved, Rebase required

#156 Fixed duplicated random field type definition in schema.xml
  lib/Resources/config/solr/schema.xml
Labels: Bug

#158 Updated README.md
  README.md
Labels: Improvement
