Repository ezsystems/ezplatform-solr-search-engine, pull requests merged in 2020-05, with the labels that each got.

#173 EZP-31420: Deleted translation from Solr when deleted from Version
  lib/Handler.php
  lib/Slot/RemoveTranslation.php
Labels: Bug, Ready for QA

#182 [Travis] Add Slack notifications
  .travis.yml
Labels: Ready for MERGE

#186 [Travis] Dropped testing using Kernel 6.7
  .travis.yml
Labels: Bug, Ready for MERGE
