Repository ezsystems/ezplatform-solr-search-engine, pull requests merged in 2020-03, with the labels that each got.

#169 EZP-31080: Created missing search Criterions
  lib/FieldMapper/ContentFieldMapper/BlockDocumentsBaseContentFields.php
  lib/Query/Common/CriterionVisitor/ObjectStateIdentifierIn.php
  lib/Query/Common/CriterionVisitor/SectionIdentifierIn.php
  lib/Resources/config/container/solr/criterion_visitors.yml
Labels: Feature, QA Approved

#170 EZP-31415: Impl. criterion visitor for CompositeCriterion
  lib/Query/Common/CriterionVisitor/CompositeCriterion.php
  lib/Resources/config/container/solr/criterion_visitors.yml
Labels: Feature, QA Approved

#174 EZP-31080: Fixed SectionIdentifier criterion to handle strings
  lib/Query/Common/CriterionVisitor/SectionIdentifierIn.php
Labels: Bug, QA Approved

#175 EZP-31220: Migrated codebase to Symfony 5
  composer.json
Labels: Ready for MERGE

#177 EZP-31517: Refactored Indexer to rely on Doctrine\DBAL
  lib/Indexer.php
  lib/Resources/config/container/solr.yml
Labels: Improvement, QA Approved

#178 EZP-31423: Refactored SetupFactory to rely on Doctrine Connection
  tests/lib/SetupFactory/LegacySetupFactory.php
Labels: Improvement
