Repository ezsystems/ezplatform-solr-search-engine, pull requests merged in 2020-01, with the labels that each got.

#164 EZP-31275: Fixed wrong tag for ContentDocumentEmptyFields
  lib/Resources/config/container/solr/field_mappers.yml
Labels: Bug, QA Approved

#161 EZP-31127: Skipped non-existing Content Types in ContentTypeIdentifier criterion
  lib/Query/Common/CriterionVisitor/ContentTypeIdentifierIn.php
  lib/Resources/config/container/solr/criterion_visitors.yml
Labels: Improvement, QA Approved

#165 EZP-31226: Added MaxDepth parameter for query location criterion and set default max depth=2 for integration tests
  lib/Query/Common/CriterionVisitor/Factory/FullTextFactoryAbstract.php
  lib/Query/Content/CriterionVisitor/Factory/ContentFullTextFactory.php
  lib/Query/Location/CriterionVisitor/Factory/LocationFullTextFactory.php
  lib/Resources/config/container/solr/criterion_visitors.yml
  tests/lib/Resources/config/cloud.yml
  tests/lib/Resources/config/common.yml
  tests/lib/Resources/config/multicore_dedicated.yml
  tests/lib/Resources/config/multicore_shared.yml
  tests/lib/Resources/config/single_core.yml
  tests/lib/Search/Query/Content/CriterionVisitor/FullTextTest.php
Labels: Bug, QA Approved, Ready for MERGE
